import {images} from '.';

export const products = [
  {
    id: 1,
    title: 'Backpack',
    description: 'nice bag',
    image: images.backpack,
    price: 30,
    quantity: 0,
  },
  {
    id: 2,
    title: 'watch',
    description: 'nice burger',
    image: images.watch,
    price: 30,
    quantity: 0,
  },
  {
    id: 3,
    title: 'Hand-Bag',
    description: 'nice carrot',
    image: images.handbag,
    price: 30,
    quantity: 0,
  },
  {
    id: 4,
    title: 'Carrots 100 g 1000g fesdsfdfsfsdf',
    description: 'nice carrot',
    image: images.shirt,
    price: 30,
    quantity: 0,
  },
  {
    id: 5,
    title: 'Mouse',
    description: 'nice carrot',
    image: images.mouse,
    price: 30,
    quantity: 0,
  },
  {
    id: 6,
    title: 'Smart Watch',
    description: 'nice carrot',
    image: images.smartwatch,
    price: 30,
    quantity: 0,
  },
  {
    id: 7,
    title: 'Leather Wallet',
    description: 'nice carrot',
    image: images.wallet,
    price: 30,
    quantity: 0,
  },
];
